version: 0.2

env:
  parameter-store:
    container_registry: "/theja/aws/docker_registry"
    ecr_repo: "/theja/pmc8/ecr_repo"
    aws_region: "/theja/aws/region"
    access_key: "/theja/aws/access_key"
    secret_key: "/theja/aws/secret_key"
    github_username: "/theja/github/username"
    github_token: "/theja/github/token"
    git_repo: "/theja/github/repo_url"

phases:
  install:
    run-as: root
    commands:
      - echo "Updating Linux packages..."
      - yum update -y
      - docker --version
      - aws --version
      - aws configure set aws_access_key_id "$access_key"
      - aws configure set aws_secret_access_key "$secret_key"
      - aws configure set region "$aws_region"
      - echo "AWS CLI configured"

  pre_build:
    run-as: root
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region "$aws_region" | docker login --username AWS --password-stdin "$container_registry"
      - echo "ECR login successful"
      - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      - echo "Grype installed"

  build:
    run-as: root
    commands:
      - |
        echo "Build started on $(date)"
        echo "Build number: $CODEBUILD_BUILD_NUMBER"
        IMAGE_TAG="$container_registry/$ecr_repo:$env_image_tag$CODEBUILD_BUILD_NUMBER"
        echo "Building Docker image $IMAGE_TAG..."
        docker build --build-arg BUILD_ENV="$build_env" -f "$docker_file" -t "$IMAGE_TAG" .
        docker images
        docker push "$IMAGE_TAG"
        grype "$IMAGE_TAG" --only-fixed
        echo "Docker build and vulnerability scan completed"

  post_build:
    run-as: root
    commands:
      - echo "Cloning GitHub repository for manifests..."
      - git clone -b main "https://$github_username:$github_token@github.com/Thejaramana186/Theja-gitops.git" "$git_path"
      - cd "$git_path"
      - |
        echo "Updating deployment YAML with new image tag..."
        PREV_TAG=$(($CODEBUILD_BUILD_NUMBER - 1))
        sed -i "s|$container_registry/$ecr_repo:$env_image_tag$PREV_TAG|$container_registry/$ecr_repo:$env_image_tag$CODEBUILD_BUILD_NUMBER|g" "$deployment_file"
      - git config --global user.email "theja4j5@gmail.com"
      - git config --global user.name "$github_username"
      - git add .
      - git commit -m "Update deployment YAML with image tag $env_image_tag$CODEBUILD_BUILD_NUMBER"
      - git push origin main
      - echo "GitOps repo updated successfully"
